name: SonarQube Analysis and Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Optional: allow manual trigger
  workflow_dispatch:

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for proper analysis
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.sirpi.co.in
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.projectName=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.java,node_modules/**,**/*.min.js,**/*.min.css
            -Dsonar.securityHotspots.enabled=true

  deploy:
    needs: sonarqube-analysis
    runs-on: ubuntu-latest
    # Only deploy on push to main (not on PRs)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Option 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # The folder containing your web app files
          branch: gh-pages  # The branch to deploy to
          

      
      - name: Deployment Status
        run: echo "Deployment complete!"
